### PR TITLE
Add height as a DecimalField to BmiForm

### PR DESCRIPTION
**Pull request by rlaszlo**
Hi @rolandgeider ,

this is the pull request for issue #146 

This PR only solves the validation problem. The calculation still using the saved height integer value.

My master branch contains commits by Jamessimas for issue 166, should I create a new commit and PR with the release branch as starting branch? If I see it correctly then you moved issue 166 to 1.7 milestone.

László

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks. How well do you know git? In such a case I would just rebase this branch onto the release branch but I'm never sure about the commads

**Comment by rolandgeider** [comment]
``git rebase release``?

**Comment by rlaszlo** [comment]
I think rebase will move all of the commits that differs from the master branch.
With git cherry-pick I can move this last commit to the release branch.

**Comment by rlaszlo** [comment]
Created the new PR with the change only, so I'm closing this.

**Pull request closed without merging**
