### PR TITLE
275 out of bounds weight error for the morbidly obese

### PR DESCRIPTION
**Pull request by azend**
Addresses issue #275

### CODE REVIEW

**Comment by rolandgeider** [comment]
Thanks for the PR!

Better make a new migration, then existing installations are upgraded too, just do a ```python manage.py makemigrations weight```, otherwise this is ready

**Comment by rolandgeider** [comment]
Oh, and don't forget to add yourself to the AUTHORS file

**Comment by azend** [comment]
Great! Now all I need is a dev machine. :)

I'll push an update when I put something together.

**Comment by rolandgeider** [comment]
OK! If you have trouble setting that up, just ask :)

**Comment by rolandgeider** [comment]
Hey! Just wanted to let you know that I've just merged this PR and added the new migration myself. I have also added you to the AUTHORS file as "Verdi R-D" but if you want something else, just tell me.

**Pull request merged**
