### PR TITLE
Improve page loading by optimizing front-end resources

### PR DESCRIPTION
**Pull request by romansp**
This PR deals with #224 issue.

Summary:
* optimize several .png files: ~70% less file size, but without actual visual difference.
* enable minification of compressed CSS via `compressor.filters.cssmin.rCSSMinFilter`

### CODE REVIEW

**Comment by rolandgeider** [comment]
Looks good. What exactly did you do to optimize the images?

**Comment by romansp** [comment]
Nothing special. I used one of many online services, however most of desktop image editors provide "Save for web" feature. There are also some CLI based tools. Usually they give very close results.

**Comment by rolandgeider** [comment]
OK, I ask because having something more or less automatic would be nice, but since there are not that many pictures that's alright

**Comment by romansp** [comment]
I'll set completely automatic flow for compressing images and svg files via gulp/grunt tasks (I was talking in #224).

Well, if I mentioned it... I would like to open PR implementing this front-end build flow with 'work in progress' label, so you could see my progress. 

Mostly because it will be helpful for me, because I'm not familiar with python/Django stack at all. I think everything will be smooth, but just in case :D

**Comment by rolandgeider** [comment]
Sure, go ahead, nothing will break! :D

**Pull request merged**
